export const MESSAGE_FETCH_REQUEST = 'MESSAGE_FETCH_REQUEST';
export const MESSAGE_FETCH_SUCCEED = 'MESSAGE_FETCH_SUCCEED';
export const MESSAGE_POST_REQUEST = 'MESSAGE_POST_REQUEST';
export const MESSAGE_POST_SUCCEED = 'MESSAGE_POST_SUCCEED';
